Criada verificação de criar diretorio, se nao existir.
brunomcr/1MLET_FASE1_TECH_CHALLENGE pull request #10
Opened 2024-04-13 13:11 UTC by brunomcr

Adicionada a logica para criar o direitorio 'arquivos_csv/', caso nao exista.

2024-04-13 18:33 UTC, garcia-pedro-hr commented
Vamos usar apenas inglês no código por favor. Tanto para nomes de variáveis, quanto para comentários e nomes de pastas/arquivos.

2024-04-13 19:17 UTC, garcia-pedro-hr requested changes
Vamos usar apenas inglês no código por favor. Tanto para nomes de variáveis, quanto para comentários e nomes de pastas/arquivos.

2024-04-14 12:48 UTC, brunomcr commented
Alterado:

- Nome do arquivo
- Variaveis
- comentarios no formato (ingles\portugues)
- Prints

2024-04-18 00:42 UTC, garcia-pedro-hr approved these changes

2024-04-18 03:50 UTC, merged