Feat: docker compose
brunomcr/1MLET_FASE1_TECH_CHALLENGE pull request #14
Opened 2024-04-24 20:41 UTC by danielaschutt

2024-04-24 22:06 UTC, garcia-pedro-hr approved these changes

2024-04-25 00:09 UTC, brunomcr requested changes
Sugeri o ajuste de comentar ou remover as linhas 15-19 do Dockerfile, e passar a execução somente para o docker-compose, descomentando a linha 14.

2024-04-25 00:09 UTC, brunomcr commented on Dockerfile
> +CMD ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
Pode comentar ou remover essas linhas, e deixar a linha(14) do docker-compose do Entreypoint descomentada.

2024-04-26 14:34 UTC, danielaschutt commented on Dockerfile
> +CMD ["uvicorn", "api_server:app", "--host", "0.0.0.0", "--port", "8000"]
Removi a do CMD, a da porta eu nao vejo motivo pra remoçao

2024-04-26 22:42 UTC, brunomcr approved these changes

2024-04-26 22:43 UTC, brunomcr commented
Pode fazer o Squash and merge por mim.

2024-04-29 14:09 UTC, merged