Feat dev api
brunomcr/1MLET_FASE1_TECH_CHALLENGE pull request #15
Opened 2024-04-25 17:21 UTC by rodrigosantili

Criando pull request do arquivo que faz o download dos arquivos

2024-04-25 17:42 UTC, brunomcr approved these changes, later dismissed

2024-04-25 18:09 UTC, garcia-pedro-hr approved these changes

2024-05-07 21:51 UTC, brunomcr requested changes
- Passar para o ingles, (comentarios e variaveis)
- Ajusta a pasta do "json_files", no repositorio esta dentro de cargas, e no codigo vai ficar fora da pasta carga. 
- Criar metodo para listar cada chamada de opt/subopt, em um unico script.

2024-05-07 22:27 UTC, brunomcr commented
Criei o script para fazer o paralelismo para cada tarefa (OPT e SUBOPT), removendo os outros scripts de carga.

2024-05-08 23:28 UTC, brunomcr approved these changes
Adicionei os comentarios no script de paralelismo, e adicionei a descricao da funcao get_data, depois da uma olhada rodrigo, por vc ter criado a funcao, se esta correto.

2024-05-11 18:49 UTC, garcia-pedro-hr approved these changes

2024-05-13 21:37 UTC, closed without merging

2024-05-13 21:38 UTC, rodrigosantili commented
Erro no readme. Criando novo pull request